---
- name: Install HAProxy
  hosts: loadbalancer
  become: true
  
  tasks:
  - name: Update APT cache
    apt:
      update_cache: yes

  - name: Install HAProxy
    apt:
      name: haproxy
      state: present

  - name: Intall python utils
    command: sudo apt-get install -y policycoreutils-python-utils

  - name: Update APT cache
    apt:
      update_cache: yes

  - name: Install Keepalived
    apt:
      name: keepalived 
      state: present