- name: Install helm and nginx ingress controller
  hosts: master[0]
  gather_facts: false
  tasks:
    - name: Install Helm
      command: sudo snap install helm --classic

    - name: Add Helm repository
      ansible.builtin.command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      changed_when: false

    - name: Update Helm repositories
      ansible.builtin.command: helm repo update
      changed_when: false

    # - name: Create ingress-controller Namespace
    #   command: kubectl create namespace ingress-controller

    - name: Deploy Ingress Nginx controller
      command: helm upgrade --install ingress-nginx ingress-nginx   --repo https://kubernetes.github.io/ingress-nginx   --namespace ingress-nginx --create-namespace  --set rbac.create=true --set controller.service.type=NodePort --set controller.metrics.enabled=true --set controller.stats.enabled=true

    - name: Verify installation
      ansible.builtin.command: kubectl get pods -n ingress-nginx
      # changed_when: false
      # when: inventory_hostname == groups['master'][0]